import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const cssPath = path.join(__dirname, "dist", "portal.css");
const outPath = path.join(__dirname, "..", "..", "src", "softap", "portal_css.h");

const css = fs.readFileSync(cssPath, "utf8");
const bytes = Buffer.byteLength(css, "utf8");

function escapeC(s) {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r/g, "")
    .replace(/\n/g, "\\n");
}

// Split into ~1 KB string fragments so the C compiler stays happy.
const chunkSize = 1000;
const parts = [];
for (let i = 0; i < css.length; i += chunkSize) {
  parts.push(escapeC(css.slice(i, i + chunkSize)));
}

const body = parts.map((p) => `  "${p}"`).join("\n");

const hdr = `/* Auto-generated by tools/softap-css — do not edit. */
#pragma once

#include <Arduino.h>

/** Purged Tailwind + DaisyUI CSS for SoftAP portal. */
static constexpr size_t kPortalCssBytes = ${bytes}u;

static const char PORTAL_CSS[] PROGMEM =
${body};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, hdr, "utf8");
console.log(`Wrote ${outPath} (${bytes} bytes CSS)`);
