#!/usr/bin/env python3
"""Crop the TAWNI owl mark and emit an RGB565 C array for the wake splash."""

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "site" / "images" / "tawni-logo.png"
OUT_H = ROOT / "src" / "ui" / "splash_logo.h"
PREVIEW = ROOT / "docs" / "tawni logo" / "splash-wake-320x170.png"

DISPLAY_W = 320
DISPLAY_H = 170
MAX_LOGO_H = 130
MAX_LOGO_W = 280


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main() -> None:
    im = Image.open(SRC).convert("RGBA")
    bbox = im.getbbox()
    if not bbox:
        raise SystemExit(f"no opaque pixels in {SRC}")
    crop = im.crop(bbox)
    cw, ch = crop.size
    scale = min(MAX_LOGO_W / cw, MAX_LOGO_H / ch)
    w = max(1, round(cw * scale))
    h = max(1, round(ch * scale))
    logo = crop.resize((w, h), Image.Resampling.LANCZOS)

    black = Image.new("RGBA", (w, h), (0, 0, 0, 255))
    composed = Image.alpha_composite(black, logo).convert("RGB")

    pixels = []
    for y in range(h):
        for x in range(w):
            r, g, b = composed.getpixel((x, y))
            pixels.append(rgb565(r, g, b))

    preview = Image.new("RGB", (DISPLAY_W, DISPLAY_H), (0, 0, 0))
    preview.paste(composed, ((DISPLAY_W - w) // 2, (DISPLAY_H - h) // 2))
    PREVIEW.parent.mkdir(parents=True, exist_ok=True)
    preview.save(PREVIEW)

    lines = [
        "// Generated by tools/gen_splash_logo.py — do not edit by hand.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"static constexpr int kSplashLogoW = {w};",
        f"static constexpr int kSplashLogoH = {h};",
        "",
        "static const uint16_t kSplashLogo[] = {",
    ]
    row = []
    for i, p in enumerate(pixels):
        row.append(f"0x{p:04X}")
        if len(row) == 12:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    lines.append("")
    OUT_H.write_text("\n".join(lines), encoding="utf-8")
    print(f"logo {cw}x{ch} -> {w}x{h}  ({len(pixels)} px)")
    print(f"wrote {OUT_H.relative_to(ROOT)}")
    print(f"wrote {PREVIEW.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
